spring.application.name=matriculas
server.port=8097
spring.datasource.url=jdbc:mysql://mysql_matricula:3306/matricula?serverTimezone=America/Lima

spring.datasource.username=usuario
spring.datasource.password=usuario123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Security
spring.security.filter.order=10

# Logging
logging.level.org.springframework.security=DEBUG
logging.level.com.example.demo=DEBUG